### PR TITLE
Bunq.Sdk support for .netstandard15

### PR DESCRIPTION
**Pull request by michielpost**
Related issue: #26

By creating a .netstandard library, this library can be used on a lot more platforms.

### CODE REVIEW

**Comment by OGKevin** [comment]
Hey @michielpost 

Thanks for your contribution. 

Do you mind following the guidelines located here: https://raw.githubusercontent.com/bunq/sdk_csharp/92f406f8cf8701e214d16c5766cbf1092f25e729/.github/PULL_REQUEST_TEMPLATE.md

In your case, the commit msg is not correct.

**Comment by michielpost** [comment]
I made this for a colleague who wanted to use the Bunq SDK on another platform and used my own commit guidelines :)
I think it can benefit more developers. It's probably easier for you to have a look at the commit, do the changes yourself in another commit and close this PR.

**Comment by OGKevin** [comment]
@michielpost closing in favour of #88. You will still be listed as contributor however 😉.

Thanks for your contribution.

**Comment by michielpost** [comment]
Fancy git stuff, thanks :)

**Pull request closed without merging**
